version: '3'

services:
  back:
    image: stfl.back
    env_file:
      - variables.env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./.m2:/var/maven/.m2
    ports:
      - 8080:8080
    container_name: stfl.back
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - variables.env
    volumes: 
      - ./mysql:/var/lib/mysql
      